M870
data-mermaid/mermaid-dash-v2 pull request #39
Opened 2024-07-17 17:57 UTC by gwan93

This feature implemented a persistent button to show how many projects passed the filters. There is also an 'x' on the button to clear all filters.

The logic to clear filters already existed in the FilterPane component, but in order to give this functionality to the clear all filters button, the logic had to be elevated into a useContext

The order of the clear filter button had to come before the ViewToggle and Zoom to Selected Data/Filtered Data buttons, so a new component called MapAndTableControls was created to contain all these buttons

2024-07-17 17:58 UTC, gwan93 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Persistient "filters applied" notification and ability to clear all.](https://trello.com/c/QeCcsHaJ/870-persistient-filters-applied-notification-and-ability-to-clear-all)

2024-07-18 13:16 UTC, alanjleonard requested changes
Looks good, however, it should also apply to the project filters as well. So if I type `fiji` in the project filter, the number of projects filtered should be reflected in the persistent notification. Clearing the notification should also clear that input.

2024-07-19 16:45 UTC, julia-rom commented on src/components/MapAndTableControls.jsx
> +    if (queryParams.has('sample_event_id')) {
can this be in a named function?

2024-07-19 17:14 UTC, julia-rom requested changes

2024-07-19 17:14 UTC, julia-rom commented on src/components/MapAndTableControls.jsx
> +    if (!map) {
would suggest 

```
if (!map || !displayedProjects || displayedProjects.length === 0) {
      return
    }
```

2024-07-19 17:14 UTC, julia-rom commented on src/components/MermaidDash.jsx
> +        let nextPageUrl = `${import.meta.env.VITE_REACT_APP_MERMAID_API_ENDPOINT}?limit=300&page=1`
would separate this out a bit for greater readability:

```
const apiEndpoint = import.meta.env.VITE_REACT_APP_MERMAID_API_ENDPOINT
    const initialUrl = `${apiEndpoint}?limit=300&page=1`
```

2024-07-19 17:14 UTC, julia-rom commented on src/components/MermaidDash.jsx
> +        let nextPageUrl = `${import.meta.env.VITE_REACT_APP_MERMAID_API_ENDPOINT}?limit=300&page=1`
`let nextPageUrl = initialUrl`

2024-07-19 17:14 UTC, julia-rom commented on src/components/MermaidDash.jsx
> +        while (nextPageUrl !== null) {
could simplify the null check .. 

```
while (nextPageUrl) { 
        const response = await fetch(nextPageUrl, {
          headers: {
            Authorization: `Bearer ${token}`,
          },
        });

        if (!response.ok) {
          console.error('Failed to fetch data:', response.status, response.statusText)
          break
        }

        const data = await response.json()
``` ...

2024-07-19 18:25 UTC, julia-rom commented on src/components/MapAndTableControls.jsx
> +    const queryParams = new URLSearchParams(location.search)
and place `const queryParams = new URLSearchParams(location.search)` under ```
const { displayedProjects, projectDataCount } = useFilterProjectsContext()
  const { isDesktopWidth } = useResponsive()
```

2024-07-19 18:47 UTC, julia-rom approved these changes

2024-07-19 18:48 UTC, merged