M896
data-mermaid/mermaid-dash-v2 pull request #40
Opened 2024-07-17 21:22 UTC by gwan93

Add a toggle to only show projects that the user is a member of

2024-07-17 21:23 UTC, gwan93 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add "Your Projects Only" filter in the filter pane](https://trello.com/c/n1RgXOV3/896-add-your-projects-only-filter-in-the-filter-pane)

2024-07-18 17:25 UTC, alanjleonard requested changes
Checking this box should enable the "zoom to filtered data" button. I also noticed that the Methods checkboxes don't enable this button either and they should.

2024-07-22 17:00 UTC, gwan93 commented on src/components/MermaidDash.jsx
> +  // const [mermaidUserData, setMermaidUserData] = useState({})
Good catch it will be removed

2024-07-22 17:11 UTC, gwan93 commented on src/context/FilterProjectsContext.jsx
> +    return projectsUserIsMemberOf.includes(projectId)
Seems to work!

2024-07-22 17:15 UTC, merged