M856
data-mermaid/mermaid-dash-v2 pull request #49
Opened 2024-08-08 20:57 UTC by gwan93

https://trello.com/c/Ik7SF0q4/856-marker-states?filter=label:dash%20app

- Change appearance of clusters to be red with white border
- When a user clicks a site, update the metrics pane to show that information about that selected site
- Add a button to the top of the metrics pane selected site to clear the selected site and remove the sample_event_id from the url params
- In mobile view if a site is selected, show the site name instead of the summarized metrics
- Some of the functionality of the metrics pane when a site is selected may be missing. I just wanted to style things first based off of the mockups. Further functionality can be added in future cards

2024-08-08 21:00 UTC, gwan93 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Marker states](https://trello.com/c/Ik7SF0q4/856-marker-states)

2024-08-13 18:06 UTC, alanjleonard requested changes
I think the stroke-width and the border can just be 1px.
![image](https://github.com/user-attachments/assets/9ff3cc49-17f7-4340-8026-e70f5446f305)

Also, it crashes on me when I click a point. The screen is just white and I get these errors:
![image](https://github.com/user-attachments/assets/b7ea9063-6a4e-4a5c-ba2e-274c11bce38d)

2024-08-15 17:50 UTC, gwan93 commented
Tagging @JBurkinshaw so reviews can be done in parallel

2024-08-15 18:19 UTC, JBurkinshaw commented on src/components/MetricsPane/MetricsPane.styles.js
> +export const SelectedSiteMetricsCardContainer = styled('div')`
Remember the shorthand for native html elements?
`styled.div`

2024-08-15 18:28 UTC, JBurkinshaw approved these changes

2024-08-15 18:53 UTC, alanjleonard requested changes
Update the stroke-width on the SVG single site markers to 1px. and use the attached png for the selected site.

![map-pin](https://github.com/user-attachments/assets/1eb340dd-e56a-43d5-89b9-98dc9a178a6f)

2024-08-15 19:22 UTC, gwan93 commented
![image](https://github.com/user-attachments/assets/ff47ebb0-0039-4914-9e46-b302f4776256)

2024-08-15 19:24 UTC, alanjleonard approved these changes

2024-08-15 19:25 UTC, merged