M975
data-mermaid/mermaid-dash-v2 pull request #58
Opened 2024-08-29 20:54 UTC by gwan93

For https://trello.com/c/GmwshTS5/975-make-a-checkbox-that-shows-projects-with-0-surveys-in-the-project-table?filter=label:dash%20app

- Add a checkbox to show projects with 0 surveys
- When the table is unmounted, it resets the `showProjectsWithNoRecords` back to false
- Added some keys (countries, organizations, years) to each project object. Previously those read from the first record of each project, but if a project was filtered down to 0 records, they wouldn't be readable. 
- Changed the order of .map() and .filter(). The .map()s filter out records (projects mapped, records filtered) which would cause some records to be filtered out too early
- Some logic in the table updated to read from the newly created countries/organizations/years keys

2024-08-30 15:25 UTC, alanjleonard requested changes
The whole button should have a hover state and toggle the checkbox. Use `cursor: pointer`.
Checking and unchecking the box, shouldn't clear how the table is sorted.

2024-08-30 18:09 UTC, gwan93 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Make a checkbox that shows projects with 0 surveys in the project table.](https://trello.com/c/GmwshTS5/975-make-a-checkbox-that-shows-projects-with-0-surveys-in-the-project-table)

2024-09-11 17:15 UTC, alanjleonard approved these changes

2024-09-12 15:15 UTC, julia-rom commented on src/context/FilterProjectsContext.jsx
> +          // These will persist even if the project has no records
is there plans to use this commented out code? can we remove it?

2024-09-12 15:21 UTC, julia-rom commented on src/components/MapAndTableControls/components/ViewToggle.jsx
> +                onClick={(e) => e.stopPropagation()}
is `(e) => e.stopPropagation()` necessary on input and label?

2024-09-12 15:21 UTC, julia-rom commented on src/context/FilterProjectsContext.jsx
> +              // project.records[0]?.tags?.some((tag) => selectedOrganizations.includes(tag.name))
same for this commented out code

2024-09-12 15:23 UTC, julia-rom commented on src/context/FilterProjectsContext.jsx
> +            const policyMappings = {
can we move `policyMappings` outside of code block maybe in the language file?

2024-09-12 15:25 UTC, julia-rom requested changes
left a few suggestions for commented out code and moving large `consts`/language mappings to an external file

2024-09-12 16:51 UTC, julia-rom commented on src/context/FilterProjectsContext.jsx
> +            const shouldOmitRecord = methodDataSharingFilters.some((filter) => {
does it make sense to name this to `omitRecord`

2024-09-12 16:52 UTC, julia-rom commented on src/context/FilterProjectsContext.jsx
> +            return !shouldOmitRecord
this is confusing .. would prefer a more descriptive var name

2024-09-12 16:53 UTC, julia-rom commented on src/context/FilterProjectsContext.jsx
> +            return !shouldOmitRecord
`omitRecordIf` (exact reason the record should be omitted)

2024-09-12 16:54 UTC, julia-rom reviewed
looking better, would like to see a more descriptive var name for `shouldOmitRecord`

2024-09-12 17:08 UTC, merged

2024-09-16 22:43 UTC, mmnoo commented
![](https://github.trello.services/images/mini-trello-icon.png) [Update tool-bar layout](https://trello.com/c/DwZux8Jf/1029-update-tool-bar-layout)