1009  change clustering sizes
data-mermaid/mermaid-dash-v2 pull request #67
Opened 2024-09-20 22:23 UTC by mmnoo

2024-09-20 22:24 UTC, mmnoo commented on src/components/MapAndTableControls/MapAndTableControls.jsx
> -
unused code. Missed linting for previous work.

2024-09-23 14:57 UTC, alanjleonard requested changes
Need to zoom so the cluster of points fills the map extent (excluding the panes). On the new dashboard, if you click on a cluster, it sometimes just splits into two and zooms a tiny bit. We want it to work like the old dashboard where it zooms in much more. 

In the screen cast:
- Old dashboard on the left, lots of zoom when clicking a marker (good)
- New dashboard on the right, very little zoom when clicking a marker (bad)

https://github.com/user-attachments/assets/ae2fc737-441c-4957-9118-4d401c33d9a8

2024-09-23 15:30 UTC, mmnoo commented
@alanjleonard I made is zoom in more. Let me know if its better.

2024-09-23 18:55 UTC, mmnoo commented
![](https://github.trello.services/images/mini-trello-icon.png) [Adjust cluster sizes and cluster onClick zoom level](https://trello.com/c/VUJUeWdz/1009-adjust-cluster-sizes-and-cluster-onclick-zoom-level)

2024-09-24 19:52 UTC, mmnoo commented on src/components/MaplibreMap.jsx
>          })
Hmm, good idea. Ill put something in the backlog for that.

2024-09-24 19:55 UTC, merged