M935 invalid dates
data-mermaid/mermaid-dash-v2 pull request #81
Opened 2024-10-16 17:48 UTC by parmvirthind

[Ticket ](https://trello.com/c/WpaBevZi/935-invalid-dates-cause-filter-to-break)

**Changes:**
- Switched out native date input with MUI DatePicker
- Updated logic so component holds local state and only updates value in context and search params if criteria is met
  - Criteria: 
    - Is a valid date (doesn't allow Nov 31st)
    - Start date is before the End Date
    - End date is after the Start Date
    - Either date is `null`
- If a date does not match criteria mentioned above, it displays a red outline.

2024-10-16 20:47 UTC, alanjleonard requested changes
**Bugs:**
- Clearing the date using the `x` doesn't seem to clear the filter.
- On mobile, when tapping on "show more filters", the screen goes blank if there's date filters applied. Chrome on android. I was on [this URL](http://localhost:3030/?sample_date_after=2000-01-01&sample_date_before=2024-10-16&lat=-5.856668442954231&lng=110.47276296509335&zoom=17.549510068870937) in the recording.

https://github.com/user-attachments/assets/edead9f5-82da-482c-a766-5eb6221a2b9e

2024-10-17 13:54 UTC, alanjleonard requested changes
There's no "clear-date" button on mobile. Probably since it shows up on hover. It can show up when the input is focused.

2024-10-17 13:57 UTC, alanjleonard commented
I can't seem to reproduce the blank screen bug. Let's ignore it for now and see if it comes up again.

2024-10-17 19:17 UTC, merged

2024-10-17 19:32 UTC, julia-rom reviewed
code looks good!