1011 make existing charts work with Mobile view
data-mermaid/mermaid-dash-v2 pull request #86
Opened 2024-12-18 20:08 UTC by mmnoo

2024-12-18 20:21 UTC, mmnoo commented
@alanjleonard this branch is ready for design review. If merged its best to review it on `develop`, otherwise you can use the feature branch.

2024-12-18 20:42 UTC, alanjleonard requested changes
- Unable to scroll past charts on touch devices since it zooms into the chart. Could probably just disable the zoom feature altogether.
- Charts with data extend off the end of the screen. (Chrome on Android, screen recording shows both issues)

https://github.com/user-attachments/assets/fc104681-9cd1-4970-b773-6245141828d7

2024-12-19 16:29 UTC, alanjleonard requested changes
1. Use either the comma separator for number of surveys/colonies or abbreviate it using k to represent 1,000. So this `267357 Colonies` turns into this `267,357 Colonies` or this `267k Colonies`. Which ever is easier for you. I think we have a function in GFCR somewhere to add the thousands separator. You can ask Julia.
2. Prevent the buttons from shifting when switching between tabs.
3. On hover, give the inactive tab a border and the secondary button hover color. 
![image](https://github.com/user-attachments/assets/5c0a3fc3-af09-4693-a78d-08d4bcee2ae6)
4. Remove the gap at the bottom of the metric pane. 
![image](https://github.com/user-attachments/assets/7e6dd15a-7b0f-49da-886e-99b10a4b4f08)

2024-12-19 19:34 UTC, julia-rom commented on src/components/MetricsPane/MetricsPane.jsx
> +          timeSeriesPanelContent={<div style={{ height: '270px' }}>Coming soon</div>}
could simplify the place holder:

`const ComingSoonPlaceholder = () => <div style={{ height: '270px' }}>Coming soon</div>`

2024-12-19 19:35 UTC, julia-rom approved these changes

2024-12-19 19:53 UTC, merged